### PR TITLE
C2 heba editing user information

### PR DESCRIPTION
**Pull request by HebaElSobky**
@AbdelrahmanAyad @Reem-Sharkawy please review the scenario to merge #97

### CODE REVIEW

**Comment by maizaied** [comment]
@HebaElSobky please check these comments:
1- if anything put in any textbox and you pressed update an alert appear saying that it is successfully updated however it is not.
2- also it just update the data one time after that it don not change

**Comment by abdelrahmanMaged** [comment]
@HebaElSobky  the previous comment was by me but i found that may was logged in on my computer by mistake

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad please check again kda i resolved the problem #97

**Comment by HebaElSobky** [comment]
@Reem-Sharkawy

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad  @Reem-Sharkawy please review the scenario #98

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad please review #97

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky you have an errorr in forms.py and it says: 
unexpected indent (forms.py, line 205)

**Comment by HebaElSobky** [comment]
La2 ya 3awad Msh l branch daah

**Pull request closed without merging**
