### PR TITLE
C1 beshoy comments

### PR DESCRIPTION
**Pull request by BeshoyAtef**
Finished the Comments and its styling 
@mohamedahmedawad93 Please review my code
@Tharwat7 @AbdelrahmanAyad Please review the branch 
#197

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
@BeshoSmile  please fix that if the user has input just space not to accept it.
if the user is not signed in please disable the comment text box 
and the bubbles are not working.
regards

**Comment by BeshoyAtef** [comment]
Screenshot from 2013-04-24 22:01:47

this is bubles are working for me so please provide me with more info to be able to fix the issue 
and will fix now the other issues

**Comment by BeshoyAtef** [comment]
@AbdelrahmanAyad I fixed all the stated issues but since the bubbles is working fine for me i dont know whats wrong

**Comment by abdelrahmanMaged** [comment]
Besho the work is perfect but here are two points to consider before i can merge your code:
1- Please validate the input so if it is just spaces you just ignore the input and show alert to the user.
2- that in order to see the bubbles the page has to be reloaded manually 
Regards,

**Comment by BeshoyAtef** [comment]
1 =point done
2- sec point WHAT ?
mesh fahem working normaly for me

On Thu, Apr 25, 2013 at 12:07 AM, abdelrahmanMaged <notifications@github.com

**Comment by abdelrahmanMaged** [comment]
I clone your branch 15 minutes ago and it does not handle the spaces.
Regarding second point when you add the comment the page refreshes
automatically however to see the bubble you to refresh it again.
Regards

**Comment by BeshoyAtef** [comment]
@mohamedahmedawad93 
please verify me

**Comment by mohamedahmedawad93** [comment]
@BeshoSmile you still have the interested view that doesn't exist issue fix it and you are ready to be merged #197

**Comment by BeshoyAtef** [comment]
please send em a screanshot

**Comment by BeshoyAtef** [comment]
@Tharwat7

**Comment by abdelrahmanMaged** [comment]
@BeshoSmile  please update the branch so we can merge it as soon as possible.
Regards,

**Comment by Tharwat7** [comment]
@BeshoSmile Ur doc verified already
please resume the rest and resolve the conflicts in order to merge u

**Comment by abdelrahmanMaged** [comment]
@BeshoSmile  please handle the case if the inpiut was just spaces and try to make the background colour match with the whole page. 
however everything else is perfect.
Regards,

**Comment by BeshoyAtef** [comment]
about teh color its intended to be a diffrent one and about the spaces ok i will handel

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=pv3YglbsjilCYo5xV7NfH6_ds-mjbCFmeF_ZntFv2Qw.eyJlbW
FpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjl
mNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MWMyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=4829f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy Atef wants to connect with you.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=pv3YglbsjilCYo5xV7NfH6_ds-mjbCFmeF_ZntFv2Qw.eyJlbW
FpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjl
mNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MWMyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=4829f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=ProfileThumb>

Beshoy Atef
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=pv3YglbsjilCYo5xV7NfH6_ds-mjbCFmeF_ZntFv2Qw.eyJlbW
FpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjl
mNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MWMyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=4829f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=ProfileName>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=pv3YglbsjilCYo5xV7NfH6_ds-mjbCFmeF_ZntFv2Qw.eyJlbW
FpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjl
mNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MWMyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&cnId=88470b98-4248-e011-88
9f-c965259bf186&emailMessageId=4829f5ef-7dc8-e211-a4c9-c701ce909180&emailType=Inv
ite&sdate=201305291636&utm_source=EmailInvite&utm_medium=Email&sendercc=EG&emailL
inkType=MainCallToAction>

reply+i-13588545-75a120c86de5c8ddd6dd3ec7d5f1767d2be229f6-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=GHCqq7XJgMGWIIU
6TygpNwFvwuaLnRvAwMdLF9MVrhU.eyJlbWFpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1
YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjlmNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=4829f5ef-7dc8-e
211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInvite&
utm_medium=Email&sendercc=EG&emailLinkType=Unsubscribe> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=1sS4rc7TPZUom6JlQ8Y_thLKHywLBdWR8QDsTYf-NoI.eyJlbW
FpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjl
mNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MWMyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODUxIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=10c9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy is waiting for you to accept this pending invitation.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=1sS4rc7TPZUom6JlQ8Y_thLKHywLBdWR8QDsTYf-NoI.eyJlbW
FpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjl
mNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MWMyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODUxIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=10c9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=ProfileT
humb>

Beshoy Atef
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=1sS4rc7TPZUom6JlQ8Y_thLKHywLBdWR8QDsTYf-NoI.eyJlbW
FpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjl
mNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MWMyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODUxIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=10c9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=ProfileN
ame>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=1sS4rc7TPZUom6JlQ8Y_thLKHywLBdWR8QDsTYf-NoI.eyJlbW
FpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjl
mNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MWMyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODUxIiwidmVyIjoiMSIsInAiOiIzIn0&cnId=88470b98-4248-e011-88
9f-c965259bf186&emailMessageId=10c9fa14-73cd-e211-be08-d229661189ee&emailType=Inv
iteFirstReminder&sdate=201306050024&utm_source=EmailInviteFirstReminder&utm_mediu
m=Email&sendercc=EG&emailLinkType=MainCallToAction>

reply+i-13588545-75a120c86de5c8ddd6dd3ec7d5f1767d2be229f6-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=0nWvfidgTyTUO6f
7dCero3WOYpbLLvwFacMrhxdGvVE.eyJlbWFpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1
YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjlmNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzcwMzkxODUxIiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=10c9fa14-73cd-e
211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_source
=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=Unsubscribe>
.

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=SqEMFzcooYY
2cuT4PTZEmXYtt_P4uK4EUVhoo79x4bI.eyJlbWFpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2
ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjlmNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmc
m9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtYzk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MW
MyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc3N1ZWRfYXQiOiIxMzcwOTk2ODI5IiwidmVyIjoiMSI
sInAiOiIzIn0&emailMessageId=0b682e48-f3d2-e211-884e-85d1397596ad&emailType=Invite
SecondReminder&sdate=201306120027&utm_source=EmailInviteSecondReminder&utm_medium
=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy Atef is still waiting to connect with you.

<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=ftux/emaili
nvitelanding?signedParameters=SqEMFzcooYY2cuT4PTZEmXYtt_P4uK4EUVhoo79x4bI.eyJlbWF
pbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjlm
Ni0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtY
zk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MWMyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc3
N1ZWRfYXQiOiIxMzcwOTk2ODI5IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=0b682e48-f3d
2-e211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120027&utm_so
urce=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Profile
Thumb>

Beshoy Atef
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=ftux/emaili
nvitelanding?signedParameters=SqEMFzcooYY2cuT4PTZEmXYtt_P4uK4EUVhoo79x4bI.eyJlbWF
pbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjlm
Ni0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtY
zk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MWMyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc3
N1ZWRfYXQiOiIxMzcwOTk2ODI5IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=0b682e48-f3d
2-e211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120027&utm_so
urce=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Profile
Name>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=SqEMFzcooYY
2cuT4PTZEmXYtt_P4uK4EUVhoo79x4bI.eyJlbWFpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2
ZGU1YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjlmNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmc
m9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtYzk2NTI1OWJmMTg2IiwidG8iOiIxZjNhZTA2Ny01MW
MyLTU0MjAtYmZlMC04MjhkMzUzOTdjZTUiLCJpc3N1ZWRfYXQiOiIxMzcwOTk2ODI5IiwidmVyIjoiMSI
sInAiOiIzIn0&emailMessageId=0b682e48-f3d2-e211-884e-85d1397596ad&emailType=Invite
SecondReminder&sdate=201306120027&utm_source=EmailInviteSecondReminder&utm_medium
=Email&sendercc=EG&emailLinkType=MainCallToAction>

reply+i-13588545-75a120c86de5c8ddd6dd3ec7d5f1767d2be229f6-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=zugJOO-8dY-daZb
Ig1IVxgsPg2s5S7legZtTN0QfPS4.eyJlbWFpbCI6InJlcGx5K2ktMTM1ODg1NDUtNzVhMTIwYzg2ZGU1
YzhkZGQ2ZGQzZWM3ZDVmMTc2N2QyYmUyMjlmNi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzcwOTk2ODI5IiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=0b682e48-f3d2-e
211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120027&utm_sourc
e=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Unsubscrib
e> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Pull request merged**
