### PR TITLE
C2 heba final user editing

### PR DESCRIPTION
**Pull request by HebaElSobky**
@AbdelrahmanAyad please review this branch instead of the other #97

### CODE REVIEW

**Comment by HebaElSobky** [comment]
@Reem-Sharkawy please review #97

**Comment by Reem-Sharkawy** [comment]
happy everything is working except for the date 
the save button is unclickable

**Comment by abdelrahmanMaged** [comment]
i am sorry that i could not see the branch earlier so @Reem-Sharkawy can review it as she already started reviewing

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad @Reem-Sharkawy resolved the unclickable save button, kindly review the code
!! thank you #97

**Comment by Reem-Sharkawy** [comment]
happy its resolved that's true , bs i can enter a date which is in 2014 :D
could you resolve this please :)

**Comment by HebaElSobky** [comment]
Yes I know, it's allowed in many sites

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad  @Reem-Sharkawy please review #97

**Comment by HebaElSobky** [comment]
@Tharwat7 kindly review the documentation #97

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93 kindly review the code #97

**Comment by Reem-Sharkawy** [comment]
@HebaElSobky scenario verified #97

**Pull request merged**
