### PR TITLE
C2 heba changing account type

### PR DESCRIPTION
**Pull request by HebaElSobky**
@mohamedahmedawad93 @mahmoudHussein please review #190

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
do youo need scenario or not??

**Comment by Tharwat7** [comment]
@HebaElSobky 
Heba please the rest of ur reviewers to verify ur work

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad please review the scenario #190

**Comment by abdelrahmanMaged** [comment]
profile is based on an old version of master please update it 
@HebaElSobky

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad @mohamedahmedawad93 @mahmoudHussein this pull request is ready to be reviewed, kindly review it #190

**Comment by abdelrahmanMaged** [comment]
@HebaElSobky kindly be notified when i am free and i want to upgrade to premium i receive an alert saying that failed however the account is being changed in the database.

One more thing please make the message in the alert more formal. 
i.e: remove the wink :) 

Regards,

**Comment by HebaElSobky** [comment]
OHH this might be. From and extra alert added just for testing..I'll check
and push again
Any other comments about scenario??

**Comment by abdelrahmanMaged** [comment]
that is what i noticed please update it and i will test again

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad i just pulled the branch and tried what you have said there isn't an alert that says fail ??
please pull the branch again and try #190

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93 kindly review #190

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad please review #190

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93 the code here is not verified #190

**Comment by abdelrahmanMaged** [comment]
kindly be notified that the samealert error presists however it updates 
fix it and mention me again. 
regards

**Comment by abdelrahmanMaged** [comment]
@HebaElSobky

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad please review #190

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad check please #190

**Comment by abdelrahmanMaged** [comment]
@HebaElSobky kindly be notified that the same error presists when i am free user and i want to upgrade to premium i still get alert saying that failed to upgarde owever in the databse it is changed.

please fix it

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad  ???
it's working 3andii

**Comment by HebaElSobky** [comment]
it is working please pull the branch again

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad please pull the whole branch again and test

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad  resolved problem please review #190

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad

**Comment by abdelrahmanMaged** [comment]
scenario verified

**Pull request merged**
