### PR TITLE
fixed a bug in subscriptions

### PR DESCRIPTION
**Pull request by abdelrahmanMaged**
@HebaElSobky please review me

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
@mohamedahmedawad93 what about you log me out of your pc :D as the pull request is made with my name on there :D

**Comment by HebaElSobky** [comment]
Howa da awad xD ?

**Comment by abdelrahmanMaged** [comment]
2aaaa

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky @abdelrahmanMaged loool

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky @BeshoSmile please review

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93 please update it to review you :)

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky i resolved all conflicts already

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93 you only fixed the part where the name of the user appears on the top right corner, right ??

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93 i did review and scenario is verified 
check with @BeshoSmile  for the code to be verified 3shan ya3melak merge

**Comment by mohamedahmedawad93** [comment]
@BeshoSmile please review

**Comment by BeshoyAtef** [comment]
Code Verified :+1:

**Pull request merged**
