### PR TITLE
C2 mai registeration1 

### PR DESCRIPTION
**Pull request by maizaied**
#93

@HebaElSobky  @mohamedahmedawad93 please review me

### CODE REVIEW

**Comment by HebaElSobky** [comment]
@maizaied i just reviewed ur modified work good job bs i need to see a BUTTON or something to go to the registration page, a user won't know that he has to type a specific url... please add a button on the homepage and let me check again :) :+1:

**Comment by maizaied** [comment]
@HebaElSobky  tharwat took the base as a user story fa whoa ell do all of this :D

**Comment by HebaElSobky** [comment]
@maizaied i can't merge it wana i can't see a button or link that directs me to your page, i asked tharwat about the new base we agreed that until it's done please do a test button or link

**Comment by maizaied** [comment]
@HebaElSobky button done :) but dont merge yet

**Comment by maizaied** [comment]
@HebaElSobky  @mohamedahmedawad93  please verify

**Comment by maizaied** [comment]
hahaha i mean review

**Comment by mohamedahmedawad93** [comment]
@maizaied an error occured when i tried to change the verify code try to handle this error

**Comment by mohamedahmedawad93** [comment]
@maizaied you have a redirecting issue when a user submits his verification code

**Comment by HebaElSobky** [comment]
@BeshoSmile did u merge this pull request ??

**Comment by BeshoyAtef** [comment]
@HebaElSobky  yes as the post u request is found in the first page of the site at the lower part

**Pull request merged**
