### PR TITLE
C2 heba status update

### PR DESCRIPTION
**Pull request by HebaElSobky**
@AbdelrahmanAyad please review the scenario and please take into consideration the 3 lines in the subscriptions.js #98

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
@HebaElSobky  kindly notice those points:
1- if the user input was just spaces or it was blank  he/she should not submit the status he must receive a warning.
2- it is adviced to has a maximum length that the user can not exceed 
Regards,

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad please review #98

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad please review #98

**Comment by HebaElSobky** [comment]
@Reem-Sharkawy  please review #98

**Comment by abdelrahmanMaged** [comment]
Kindly be notified that the server does not run i get that error Could not
import tager_www.views.testRender. View does not exist in module tager_www

regards

**Comment by HebaElSobky** [comment]
Da eh da ba2a
Cooment the URL l byru7 3aliiha that's not mine

**Comment by BeshoyAtef** [comment]
@HebaElSobky i am afraid to tell you ano thats not my url

**Comment by BeshoyAtef** [comment]
please note that the same pic is added twice 
i know i am not ur reviewer but if yu can remove one of them to reduce the size  going to be added to the repo that will be great

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad try to git fetch, git branch -a the project is perfectly fine and running please review #98 
@Reem-Sharkawy please try to review this

**Comment by abdelrahmanMaged** [comment]
i already reviewed and everything is perfect except one thing.
The warning label does not match match the scenario itself.
for e.g: when the user doesn't type anything the label says status can not
be spaces.
please change that :)
Reagrds,

**Comment by HebaElSobky** [comment]
Ehh

**Comment by HebaElSobky** [comment]
Fin l Moshkila ??
L bta3 bytla3 aho

**Comment by abdelrahmanMaged** [comment]
it appears bs the label is misleading.

For example when the user type nothing the label will appear with the text
status can not be spaces however she/he did not type anything already

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad check again #98

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93 please review the code #98

**Comment by HebaElSobky** [comment]
@Tharwat7 please review the documentation #98

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93 kindly review the code and merge it #98

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky line 65 in urls.py is causing an error, remove this line

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky changing profile picture is not working, it says url not found

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93 merged the branch with master and resolved conflicts #98 kindly merge please

**Comment by abdelrahmanMaged** [comment]
scenario verfied

**Comment by maizaied** [comment]
i need el squence digram :D

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93 kindly merge the branch please #98

**Comment by HebaElSobky** [comment]
@mohamedahmedawad93

**Comment by mohamedahmedawad93** [comment]
@HebaElSobky verified your code #98

**Comment by BeshoyAtef** [comment]
@mohamedahmedawad93 
@HebaElSobky 
This pull request causes some major css errors in main , and viewpost , and registration 
how this can be merged ?

**Comment by mohamedahmedawad93** [comment]
@BeshoSmile it was scenario, uml and documentation verified before i merged it

**Pull request merged**
