### PR TITLE
added the edit post removed methods

### PR DESCRIPTION
**Pull request by abdelrahmanMaged**
@HebaElSobky  please review

### CODE REVIEW

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad branch name ??

**Comment by abdelrahmanMaged** [comment]
c1_abdelrahman_edit_post

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad no alerts appear ?

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad la2ethom :D

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad scenario verified :+1:

**Comment by abdelrahmanMaged** [comment]
u dropped my heart :P

**Comment by HalaKamal** [comment]
@AbdelrahmanAyad  please when you finish your diagram tag me to review it ,but tag me in the issue and the pull request

**Pull request merged**
