### PR TITLE
Fixed Post State method according to new conventions

### PR DESCRIPTION
**Pull request by Tharwat7**
@BeshoSmile @abdelrahmanMaged 

Please review me and merge the code

### CODE REVIEW

**Comment by BeshoyAtef** [comment]
will test it now and check the code

**Comment by abdelrahmanMaged** [comment]
@Tharwat7  please update the branch so we can review it

**Comment by Tharwat7** [comment]
@mohamedahmedawad93 Please review and merge

**Comment by HalaKamal** [comment]
tage me when u finish the diagram  @Tharwat7

**Pull request merged**
