### PR TITLE
admin can hide posts

### PR DESCRIPTION
**Pull request by abdelrahmanMaged**
@HebaElSobky 
@BeshoSmile 
@Tharwat7 
please review

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
@HebaElSobky please review

**Comment by abdelrahmanMaged** [comment]
@maizaied  please check the tests and add yours :D

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad kindly note that i can't hide the post, or can't find the button

**Comment by abdelrahmanMaged** [comment]
Can you please clone again
as i tested the branch from another clone and it is working fine

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad  okay it worked :+1: 
the number of posts dii tba3ak ??

**Comment by abdelrahmanMaged** [comment]
number of posts a??

**Comment by HebaElSobky** [comment]
number pf reports sorry!!

**Comment by abdelrahmanMaged** [comment]
i just display as a help for the admin to know the number of reports this
post reached

**Comment by HebaElSobky** [comment]
@AbdelrahmanAyad scenario verified

**Comment by abdelrahmanMaged** [comment]
can you please merge :D

**Comment by HebaElSobky** [comment]
i was just doing the last test and your good to go :+1:

**Comment by BeshoyAtef** [comment]
:+1:

**Pull request merged**
