### PR TITLE
C3 ahmed facebook login

### PR DESCRIPTION
**Pull request by ahmedshireef**

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
@iBebarz kindly be notified that when i am testing i git this bug with my first test.
If i logged in with my facebook account and i tried to sign up with the same email in fb i get in an error saying that the email is used.

**Comment by abdelrahmanMaged** [comment]
@iBebarz kindly be notified that it is 4 pm right and you still did not correct your code

**Comment by ahmedshireef** [comment]
Please review and merge, the button is green now @ 0254 @abdelrahmanMaged  @Reem-Sharkawy  @nadeembarakat  @mohamedhammad89  @saraismail1234  @HalaKamal

**Comment by ahmedshireef** [comment]
@HebaElSobky If you are available please review, the button is green now

**Comment by abdelrahmanMaged** [comment]
do not worry i am here i will review it in 15 minutes :)

**Comment by ahmedshireef** [comment]
Thx, Allah ma3ak

**Comment by abdelrahmanMaged** [comment]
@iBebarz i know that you need to merge bs these are the bugs that i found:

1- after pressing just an account being created but the actual login is not performed
2- if i tried to signuo with the same email i get a message saying that this email is already used before 
3- if i am already logged in to facebook in anyother tab i do not get anything daying that i am logged in successfully
4- the user that is initialized in the database is being unverified however login with facebook should make this user verified. 

Please fix this bugs :D

**Comment by ahmedshireef** [comment]
I dont understand how an actual login is not performed, do u get your
facebook name beside the settings button?

On Thu, May 2, 2013 at 3:12 AM, abdelrahmanMaged
notifications@github.comwrote:

> @iBebarz https://github.com/iBebarz i know that you need to merge bs
> these are the bugs that i found:
> 
> 1- after pressing just an account being created but the actual login is
> not performed
> 2- if i tried to signuo with the same email i get a message saying that
> this email is already used before
> 3- if i am already logged in to facebook in anyother tab i do not get
> anything daying that i am logged in successfully
> 4- the user that is initialized in the database is being unverified
> however login with facebook should make this user verified.
> 
> Please fix this bugs :D
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/239#issuecomment-17315816
> .

## 

Thx..

Ahmed M. El Shireef

**Comment by ahmedshireef** [comment]
verification being added

**Comment by ahmedshireef** [comment]
but why would i verify an email returned from facebook?

**Comment by abdelrahmanMaged** [comment]
as in our website the unverified user can not post or comment or do
anything hence if a user log in with facebook abd was not verified it will
be useless and the owner said that he just wants people to log in with
facebook so we have to make the process easier.

and what i mean by actual login is that i do not find his name next to the
settings or anything

**Comment by mahmoudHussein** [comment]
When u r adding this FB user to the database just change the is_verified from false to true ! Then save ! 
Sent from my BlackBerry® from Vodafone

-----Original Message-----

**Comment by ahmedshireef** [comment]
The branch is ready to merge, and its around 24 hours since it was last ready to merge,

Please review and merge @abdelrahmanMaged @Reem-Sharkawy @nadeembarakat

**Comment by abdelrahmanMaged** [comment]
yes it was ready since 24 hours but if you checked you will find that i
reviewed and i send you my comments 15 hours ago and you did not work
regarding my points.
However i will not be able to review the branch now i will review it in an
hour or something.

Regards,

**Comment by ahmedshireef** [comment]
Your comments were invalid my dear, another developer tested the branch
contents and it was working alike what you stated in your comments. Please
try to pull again and review.

On Fri, May 3, 2013 at 3:41 AM, abdelrahmanMaged
notifications@github.comwrote:

> yes it was ready since 24 hours but if you checked you will find that i
> reviewed and i send you my comments 15 hours ago and you did not work
> regarding my points.
> However i will not be able to review the branch now i will review it in an
> hour or something.
> 
> Regards,
> 
> On 3 May 2013 03:38, iBebarz notifications@github.com wrote:
> 
> > The branch is ready to merge, and its around 24 hours since it was last
> > ready to merge,
> > 
> > Please review and merge @abdelrahmanMaged<
> > https://github.com/abdelrahmanMaged>
> > @Reem-Sharkawy https://github.com/Reem-Sharkawy @nadeembarakat<
> > https://github.com/nadeembarakat>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/DinaSaad/sharesoft-13/pull/239#issuecomment-17374842>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/239#issuecomment-17374893
> .

## 

Thx..

Ahmed M. El Shireef

**Comment by ahmedshireef** [comment]
However i considered the verification issue and fixed it. I think you just
need to check wether if the branch pull has brought the contents correctly
or not.

On Fri, May 3, 2013 at 3:42 AM, Ahmed M. El Shireef
ahmedshireef@gmail.comwrote:

> Your comments were invalid my dear, another developer tested the branch
> contents and it was working alike what you stated in your comments. Please
> try to pull again and review.
> 
> On Fri, May 3, 2013 at 3:41 AM, abdelrahmanMaged <notifications@github.com
> 
> > wrote:
> > 
> > yes it was ready since 24 hours but if you checked you will find that i
> > reviewed and i send you my comments 15 hours ago and you did not work
> > regarding my points.
> > However i will not be able to review the branch now i will review it in
> > an
> > hour or something.
> > 
> > Regards,
> > 
> > On 3 May 2013 03:38, iBebarz notifications@github.com wrote:
> > 
> > > The branch is ready to merge, and its around 24 hours since it was last
> > > ready to merge,
> > > 
> > > Please review and merge @abdelrahmanMaged<
> > > https://github.com/abdelrahmanMaged>
> > > @Reem-Sharkawy https://github.com/Reem-Sharkawy @nadeembarakat<
> > > https://github.com/nadeembarakat>
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/DinaSaad/sharesoft-13/pull/239#issuecomment-17374842>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/239#issuecomment-17374893
> > .
> 
> ## 
> 
> Thx..
> 
> Ahmed M. El Shireef

## 

Thx..

Ahmed M. El Shireef

**Comment by abdelrahmanMaged** [comment]
Since my comments are invalid and another reviewer tested the branch so
this reviewer can complete the process of reviewing as i can not review
something that someone already reviewing it.
regards,

**Comment by ahmedshireef** [comment]
N
o other reviewer tested the branch, another developer tested the branch as
an unofficial test.

Please pull and review.

Regards

On Fri, May 3, 2013 at 3:44 AM, abdelrahmanMaged
notifications@github.comwrote:

> Since my comments are invalid and another reviewer tested the branch so
> this reviewer can complete the process of reviewing as i can not review
> something that someone already reviewing it.
> regards,
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/239#issuecomment-17374971
> .

## 

Thx..

Ahmed M. El Shireef

**Comment by abdelrahmanMaged** [comment]
kindly be notified that these two bugs exists::

1- if i already a user in the site "i sign up regularly from the website "
and i tried to log in with the facebook i will get an error.
IntegrityError at /facebook/login/done/

column email is not unique

2- if the user sign in with facebook and then tried to sign up with the
same account the user gets an error saying that this email address already
exists.

P.s: I cloned your branch in a new repo to make sire that i am reviewing
the most up to date version.

**Comment by ahmedshireef** [comment]
Dear Abdo, these two bugs are normal according to the user story, facebook login is used to make users login easy into the site without doing any registration data entry.
A user who signs up to the site using the traditional way would not be able to login with facebook unless we handle connecting the normal user's account to the facebook, and that is not a part of the story.

Regards

**Comment by ahmedshireef** [comment]
NB: Dear Abdelrahman please consider the following too:
A user who has signed in with facebook has already done a sign up and created an account, why would he try to create another account with the same email? This is not a part of the user story.

Regards

**Comment by abdelrahmanMaged** [comment]
to me it is a part of the story as i can not merge such a code to the
master that i know it will collapse by a simple click.

and i am sire that this all of what i said is part of the story as the
doctor explicitly said so.
morover this is story is from sprint 0 so coding in this story is in
progress since 5-6 weeks so by now i am expecting that at least it serve
such a functionality.

I am sorry but i will not verify the scenario until these bugs are fixed.
Regards,

**Comment by ahmedshireef** [comment]
@Tharwat7

**Comment by Reem-Sharkawy** [comment]
image
i tried calling you alot , please reply , i have this error , how can i resolve it ?!
or please resolve it and inform me

**Comment by ahmedshireef** [comment]
@HalaKamal UMLs added

**Comment by ahmedshireef** [comment]
https://docs.google.com/file/d/0B8AlOcZvuZexeGNYZ1pySGFIdzg/edit @HalaKamal

**Comment by HalaKamal** [comment]
@iBebarz must add life time to theuser actor

**Comment by HalaKamal** [comment]
@iBebarz the return is doted not lined

**Comment by HalaKamal** [comment]
@iBebarz there must be life times not a huge long one , make then parts when one finish the other starts and the last one ends before the life time of the acor

**Comment by HalaKamal** [comment]
@iBebarz and the system tager its wrong write the corrected one folder name, and also for facebook service

**Comment by HalaKamal** [comment]
uml reopended

**Pull request closed without merging**
