### PR TITLE
Annoymous trials

### PR DESCRIPTION
**Pull request by mahmoudHussein**
@BeshoSmile @mohamedahmedawad93 please review the code

### CODE REVIEW

**Comment by BeshoyAtef** [comment]
nice code :+1:

**Comment by BeshoyAtef** [comment]
can’t automatically merge this pull request.

**Comment by mahmoudHussein** [comment]
@BeshoSmile @mohamedahmedawad93 this file can be automatically merged now so can you please merge!

**Comment by BeshoyAtef** [comment]
the branch is awesome
 some remarks to consider
-the nav bar is 2 lines tager in a line and the other in another line (when loged in)
-some links not working  (contact and Advanced search)
screenshot from 2013-05-03 11 06 30

**Comment by BeshoyAtef** [comment]
when loged in the nav is Search then adv search 
but when not logged in its 
Adv search then search

**Comment by mahmoudHussein** [comment]
Will correct that now isa no problem 
Sent from my BlackBerry® from Vodafone

-----Original Message-----

**Comment by mahmoudHussein** [comment]
@BeshoSmile  added the stuff so please merge.

**Pull request merged**
