### PR TITLE
C1 tharwat sprint2 tager css

### PR DESCRIPTION
**Pull request by Tharwat7**
@abdelrahmanMaged @BeshoSmile 
Please review what i have done so far and merge since all the company will be using the base...

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
@Tharwat7 please correct the following mistakes:
1- The blue words in the navbar it is so big and looks not good.
2- there are about 3 broken links in the navbar 
3- on the top right side of the navbar it is written tharwat however this is not the name of the user that i logged in with.

Regards,

**Comment by abdelrahmanMaged** [comment]
@Tharwat7  one more thing please fix the footer. 
e.g "sharesoft-13" must be at the bottom of the website

**Comment by Tharwat7** [comment]
@abdelrahmanMaged All errors have been fixed

**Comment by abdelrahmanMaged** [comment]
navbar working properly @Tharwat7 
regards,

**Comment by HalaKamal** [comment]
when you finish your diagram tage me to review @Tharwat7

**Pull request merged**
