### PR TITLE
C2 mahmoud rating seller

### PR DESCRIPTION
**Pull request by mahmoudHussein**
@maizaied @HebaElSobky @mohamedahmedawad93 please review and give me feed back #106

### CODE REVIEW

**Comment by BeshoyAtef** [comment]
#106

**Comment by mahmoudHussein** [comment]
@maizaied @mohamedahmedawad93 @HebaElSobky please review my code !

**Comment by Tharwat7** [comment]
@mahmoudHussein please link your commits to the issue :)

**Comment by HebaElSobky** [comment]
@mahmoudHussein  Scenario is reviewed and it works. good to go

**Pull request merged**
