### PR TITLE
C2 mahmoud interacted with

### PR DESCRIPTION
**Pull request by mahmoudHussein**
@maizaied @HebaElSobky @mohamedahmedawad93 please check that the interacted with method is working and merge please !

### CODE REVIEW

**Comment by mahmoudHussein** [comment]
#221

**Comment by abdelrahmanMaged** [comment]
@mahmoudHussein  it is a reminder that your branch msh mnawar green hat l master w mergo 3ndk w push :D
yla y 3m mehaesk aho :P

**Comment by HebaElSobky** [comment]
@mahmoudHussein please pull the new master and update

**Comment by Tharwat7** [comment]
@mahmoudHussein if ur reviewers didnt review by 6 hours since the time u pulled the request please re-shuffle them and ask a diff reviewer

**Comment by Tharwat7** [comment]
@mahmoudHussein and where is the link to ur issue number?

**Comment by mahmoudHussein** [comment]
look up top dear tharwat ! 

@mohamedahmedawad93 @maizaied @HebaElSobky please review me ! #221

**Comment by mohamedahmedawad93** [comment]
@mahmoudHussein please handel the spaces and wrong insertions in the add buyer text box

**Comment by mohamedahmedawad93** [comment]
@mahmoudHussein please pull the new master and merge it with your branch

**Comment by mohamedahmedawad93** [comment]
@mahmoudHussein i verified your code #221

**Comment by mahmoudHussein** [comment]
@mohamedahmedawad93 @HebaElSobky added the add buyer constraint ... please review !

**Comment by mahmoudHussein** [comment]
@HebaElSobky @Tharwat7 please review me !!

**Comment by HebaElSobky** [comment]
@mahmoudHussein please update the branch and check the error i told u about

**Comment by HebaElSobky** [comment]
@mahmoudHussein  scenario verified

**Pull request merged**
