### PR TITLE
C3 ahmed twitter login

### PR DESCRIPTION
**Pull request by ahmedshireef**
Please review @Reem-Sharkawy  @saraismail1234  @mohamedhammad89  @nadeembarakat

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
@iBebarz the moment i started to review the branch i got this error:
No module named tweepy 

also please consider updating your branch :)

**Comment by ahmedshireef** [comment]
This is because twitter works with the app tweepy, which was on the master.
I will push the app and lets see

**Comment by abdelrahmanMaged** [comment]
ok i need a branch that i can review please :D

**Comment by ahmedshireef** [comment]
Sure, right away

On Wed, May 1, 2013 at 1:40 AM, abdelrahmanMaged
notifications@github.comwrote:

> ok i need a branch that i can review please :D
> 
> On 1 May 2013 01:39, iBebarz notifications@github.com wrote:
> 
> > This is because twitter works with the app tweepy, which was on the
> > master.
> > I will push the app and lets see
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17261137>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17261152
> .

## 

Thx..

Ahmed M. El Shireef

**Comment by abdelrahmanMaged** [comment]
bs please 3latool 3shan ana wlahy msh adr w 3aez anam :D

**Comment by ahmedshireef** [comment]
You are clear to go, sammy keda we etwakel 3ala Allah :D

On Wed, May 1, 2013 at 1:42 AM, Ahmed M. El Shireef
ahmedshireef@gmail.comwrote:

> Sure, right away
> 
> On Wed, May 1, 2013 at 1:40 AM, abdelrahmanMaged <notifications@github.com
> 
> > wrote:
> > 
> > ok i need a branch that i can review please :D
> > 
> > On 1 May 2013 01:39, iBebarz notifications@github.com wrote:
> > 
> > > This is because twitter works with the app tweepy, which was on the
> > > master.
> > > I will push the app and lets see
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17261137>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17261152
> > .
> 
> ## 
> 
> Thx..
> 
> Ahmed M. El Shireef

## 

Thx..

Ahmed M. El Shireef

**Comment by abdelrahmanMaged** [comment]
same error exists.

to be clear this is the branch that i review:
C3_Ahmed_Twitter_login
am i right??

**Comment by ahmedshireef** [comment]
do u have the folder tweepy beside tager_www?

On Wed, May 1, 2013 at 1:46 AM, abdelrahmanMaged
notifications@github.comwrote:

> same error exists.
> 
> to be clear this is the branch that i review:
> C3_Ahmed_Twitter_login
> am i right??
> 
> On 1 May 2013 01:44, iBebarz notifications@github.com wrote:
> 
> > You are clear to go, sammy keda we etwakel 3ala Allah :D
> > 
> > On Wed, May 1, 2013 at 1:42 AM, Ahmed M. El Shireef
> > ahmedshireef@gmail.comwrote:
> > 
> > > Sure, right away
> > > 
> > > On Wed, May 1, 2013 at 1:40 AM, abdelrahmanMaged <
> > > notifications@github.com
> > > 
> > > > wrote:
> > > > 
> > > > ok i need a branch that i can review please :D
> > > > 
> > > > On 1 May 2013 01:39, iBebarz notifications@github.com wrote:
> > > > 
> > > > > This is because twitter works with the app tweepy, which was on the
> > > > > master.
> > > > > I will push the app and lets see
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > 
> > > > https://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17261137>
> > > > 
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17261152>
> > > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Thx..
> > > 
> > > Ahmed M. El Shireef
> > 
> > ## 
> > 
> > Thx..
> > 
> > Ahmed M. El Shireef
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17261263>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17261339
> .

## 

Thx..

Ahmed M. El Shireef

**Comment by abdelrahmanMaged** [comment]
just a secod i am reviewing someone else now

**Comment by abdelrahmanMaged** [comment]
@iBebarz  update the branch please so i can review it

**Comment by ahmedshireef** [comment]
i just did

On Wed, May 1, 2013 at 2:03 AM, abdelrahmanMaged
notifications@github.comwrote:

> @iBebarz https://github.com/iBebarz update the branch please so i can
> review it
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17261829
> .

## 

Thx..

Ahmed M. El Shireef

**Comment by ahmedshireef** [comment]
so do u have tweepy folder next to tager_www?

On Wed, May 1, 2013 at 2:05 AM, Ahmed M. El Shireef
ahmedshireef@gmail.comwrote:

> i just did
> 
> On Wed, May 1, 2013 at 2:03 AM, abdelrahmanMaged <notifications@github.com
> 
> > wrote:
> > 
> > @iBebarz https://github.com/iBebarz update the branch please so i can
> > review it
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17261829
> > .
> 
> ## 
> 
> Thx..
> 
> Ahmed M. El Shireef

## 

Thx..

Ahmed M. El Shireef

**Comment by abdelrahmanMaged** [comment]
would you please make sure that you rpull request is green as till now it
is grey please do that as soon as possible

**Comment by ahmedshireef** [comment]
@abdelrahmanMaged Please review, the button is now green

**Comment by abdelrahmanMaged** [comment]
ok

**Comment by abdelrahmanMaged** [comment]
@iBebarz  dear ahmed kindly find the following notice:
1- When i log in with twitter the user is not being logged in. i test it with many cases and i found out that the user is not logged in.
2- Since we agreed on a specific criteria for the scenario reviewing and hence i am now your reviewer so i am sorry to say that this pull request do not serve the core functionality which is the login itself. so the final decision now will be for Tharwat  to identify what should be done next. Regards,
PLease be notified that also log in with facebook until now is not on the master and this method was supposed to be there about 3 weeks ago. 
@Tharwat7 
Regards,

**Comment by ahmedshireef** [comment]
@abdelrahmanMaged dear abdo regarding the facebook login, it was on the master on time and was working even during the demo, however the changes that happened with the home.html caused the function to be disconnected from the button. However this issue is simple, it will be resolved soon.

**Comment by Tharwat7** [comment]
@iBebarz 
Regarding fb since its a small issue and is working there is no problem.. however this button should be working max by tom morning for everyone to use
Max by tom morning

**Comment by Tharwat7** [comment]
@iBebarz 

However, regarding twitter the review failed and confirmed that it is not working and way past its deadline itll bereshuffled

**Comment by ahmedshireef** [comment]
the twitter creates the user in the database

On Wed, May 1, 2013 at 3:00 AM, Tharwat7 notifications@github.com wrote:

> @iBebarz https://github.com/iBebarz
> 
> However, regarding twitter the review failed and confirmed that it is not
> working and way past its deadline itll bereshuffled
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17263530
> .

## 

Thx..

Ahmed M. El Shireef

**Comment by Tharwat7** [comment]
Ur scenario reviewer informed me that the complete process failed

**Comment by ahmedshireef** [comment]
Agreed

On Wed, May 1, 2013 at 3:21 AM, Tharwat7 notifications@github.com wrote:

> Ur scenario reviewer informed me that the complete process failed
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DinaSaad/sharesoft-13/pull/237#issuecomment-17264036
> .

## 

Thx..

Ahmed M. El Shireef

**Comment by Reem-Sharkawy** [comment]
what will be done so far regarding this issue ?!

**Comment by abdelrahmanMaged** [comment]
from what i know that mohamed is now working on this issue if it is not
done we will not add it as it is low priority for the PO

**Pull request closed without merging**
