### PR TITLE
added my part corrected with the title and picture to appear in a shared post

### PR DESCRIPTION
**Pull request by saraismail1234**
@Reem-Sharkawy @iBebarz @nadeembarakat @mohamedhammad89

### CODE REVIEW

**Comment by mohamedhammad89** [comment]
it seems there is a problem in the from end every time i switch to your branch and run the server there is an error in base.html please recheck your code

**Comment by Reem-Sharkawy** [comment]
sara check again , the server is not running

**Comment by Reem-Sharkawy** [comment]
#109

**Comment by Reem-Sharkawy** [comment]
sara pull master , and push again after resolving any errors 
image

**Pull request closed without merging**
