### PR TITLE
C2 heba public private option

### PR DESCRIPTION
**Pull request by HebaElSobky**
@mohamedahmedawad93 @AbdelrahmanAyad @mahmoudHussein please review #189

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
@HebaElSobky kindly be notified that you need to remove the head and the tails from the page.
moreover kindly be notified that all the edit buttons are not working.
kindly update them as soon as possible
Regards,

**Comment by HebaElSobky** [comment]
yes i didnt know that beshoy changed in the function i worked on it now and
i'll push now

**Comment by abdelrahmanMaged** [comment]
@mahmoudHussein i added the documentation #189

**Comment by HebaElSobky** [comment]
@mahmoudHussein sorry abdelrahman was didn't sign out from my laptop!! mahmoud documentation is ready to reviewed #189

**Comment by abdelrahmanMaged** [comment]
@HebaElSobky kindly be notified that the data is hidden successfully however for the user himself he/she can view it however i anybody else he can not.

also the user should have the option to unhide the data whenever he/she wish
regards,

**Comment by HebaElSobky** [comment]
ehh ?

On Tue, Apr 30, 2013 at 11:16 PM, abdelrahmanMaged <notifications@github.com

**Comment by BeshoyAtef** [comment]
happy those stuff r on master walla la2 ?

**Pull request closed without merging**
