### PR TITLE
C1 abdelrahman wishlist

### PR DESCRIPTION
**Pull request by abdelrahmanMaged**
@BeshoSmile please review the code i handled the error of the anoynmous user

### CODE REVIEW

**Comment by Reem-Sharkawy** [comment]
where is the issue regarding this branch , because I can't find it

**Comment by abdelrahmanMaged** [comment]
which branch??

**Comment by Reem-Sharkawy** [comment]
c1_abdelrahman_wishlist

**Comment by abdelrahmanMaged** [comment]
l branch d is already merged 5las :D wl issue is closed asln :D

**Comment by Reem-Sharkawy** [comment]
(Y)

**Comment by BeshoyAtef** [comment]
Verified

**Comment by HalaKamal** [comment]
when you finish diagram tag me to review @AbdelrahmanAyad

**Comment by HalaKamal** [comment]
@AbdelrahmanAyad  your diagram must be fixed the html must be in templates, also how does the lif time ends of open post page and still the render didn't return post.
uml is reopened not veirified

**Comment by HalaKamal** [comment]
@AbdelrahmanAyad @abdelrahmanMaged  by the way i'm your reviewer of uml diagram i'm not supposed to look after you that you uploaded your things to review it u must tag me 
regards.

**Pull request merged**
