### PR TITLE
C2 mai sms

### PR DESCRIPTION
**Pull request by maizaied**
@mahmoudHussein  @mohamedahmedawad93  @HebaElSobky  please review me :D

### CODE REVIEW

**Comment by maizaied** [comment]
please review me  @mahmoudHussein  @HebaElSobky  @mohamedahmedawad93

**Comment by mahmoudHussein** [comment]
@maizaied i'll review you now isa

**Comment by mohamedahmedawad93** [comment]
@maizaied mai update your branch

**Comment by maizaied** [comment]
thank u for reviwing @HebaElSobky  please review me

**Comment by maizaied** [comment]
@HebaElSobky pleaseee review me :)

**Comment by HebaElSobky** [comment]
@maizaied scenario verified

**Pull request merged**
