### PR TITLE
Mahmoud adding removed master stuff

### PR DESCRIPTION
**Pull request by mahmoudHussein**
@BeshoSmile @mohamedahmedawad93 please review and merge the removed stuff !

### CODE REVIEW

**Comment by mahmoudHussein** [comment]
@HebaElSobky

**Comment by Tharwat7** [comment]
@mohamedahmedawad93  Please review his scenario as soon as possible

**Comment by HebaElSobky** [comment]
@mahmoudHussein you forgot to hook the issue to the pull request, please do so :)

**Comment by mahmoudHussein** [comment]
there is no hook to any issue as there is no issue for that because i just
added something that was removed .

**Comment by HebaElSobky** [comment]
Okaay I'm review right now :)

Sent from my iPhone,
Heba A. El-Sobky :)

**Comment by HebaElSobky** [comment]
@mahmoudHussein okaay so the post button and the stars were hidden behind the profile picture and i couldn't see them!! just cut and past the div of the stars with the button and paste it just after the div with id="box1" :)

**Comment by HebaElSobky** [comment]
@mahmoudHussein do that and tell me to review again

**Comment by mahmoudHussein** [comment]
@HebaElSobky done ! please check !

**Comment by BeshoyAtef** [comment]
@mahmoudHussein please wait for the profile update

**Comment by HebaElSobky** [comment]
Don't worry Ana l ba-merge Ana 3amla 7esabii (Y)
Bs mahmoud do what I told u about fl stars

Sent from my iPhone,
Heba A. El-Sobky :)

**Comment by BeshoyAtef** [comment]
dodo check fb i sent a pic of where the stars should go
happy i am jst trying to avoid any conflicts fl css and html

**Comment by HebaElSobky** [comment]
I thought about it ;)) before u do =P

Sent from my iPhone,
Heba A. El-Sobky :)

**Comment by mahmoudHussein** [comment]
Mm...happy I did as you told me and I added it after the div with ID box1 and besho when is the other profile gonna be posted because that's sprint 1 stuff and it should have been on the master already so can you please hurry up with it ?! 
Sent from my BlackBerry® from Vodafone

-----Original Message-----

**Comment by HebaElSobky** [comment]
@mahmoudHussein okaay i just reviewed @BeshoSmile he just needs to add a placeholder and both of you are ready to be merged :+1:

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=ewB-YVFMHMCUkTwbbhppytVpVg-UHahPPBxBP-J6mNM.eyJlbW
FpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJ
lNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05ZjVkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=5529f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy Atef wants to connect with you.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=ewB-YVFMHMCUkTwbbhppytVpVg-UHahPPBxBP-J6mNM.eyJlbW
FpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJ
lNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05ZjVkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=5529f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=ProfileThumb>

Beshoy Atef
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=ewB-YVFMHMCUkTwbbhppytVpVg-UHahPPBxBP-J6mNM.eyJlbW
FpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJ
lNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05ZjVkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=5529f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=ProfileName>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=ewB-YVFMHMCUkTwbbhppytVpVg-UHahPPBxBP-J6mNM.eyJlbW
FpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJ
lNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05ZjVkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&cnId=88470b98-4248-e011-88
9f-c965259bf186&emailMessageId=5529f5ef-7dc8-e211-a4c9-c701ce909180&emailType=Inv
ite&sdate=201305291636&utm_source=EmailInvite&utm_medium=Email&sendercc=EG&emailL
inkType=MainCallToAction>

reply+i-13736431-b00e539f49385a604433a684a46d078b57305be7-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=KJhV7RxihMNlGvv
iGQ5lKgd0HhjTO9N3DuMrR9ACfiM.eyJlbWFpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4
NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJlNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=5529f5ef-7dc8-e
211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInvite&
utm_medium=Email&sendercc=EG&emailLinkType=Unsubscribe> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=riCfzGUj940Cl02TziB6svJUv2k4kM162GhGaA3b80w.eyJlbW
FpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJ
lNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05ZjVkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODkwIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=0ec9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy is waiting for you to accept this pending invitation.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=riCfzGUj940Cl02TziB6svJUv2k4kM162GhGaA3b80w.eyJlbW
FpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJ
lNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05ZjVkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODkwIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=0ec9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=ProfileT
humb>

Beshoy Atef
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=riCfzGUj940Cl02TziB6svJUv2k4kM162GhGaA3b80w.eyJlbW
FpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJ
lNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05ZjVkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODkwIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=0ec9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=ProfileN
ame>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=riCfzGUj940Cl02TziB6svJUv2k4kM162GhGaA3b80w.eyJlbW
FpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJ
lNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05ZjVkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODkwIiwidmVyIjoiMSIsInAiOiIzIn0&cnId=88470b98-4248-e011-88
9f-c965259bf186&emailMessageId=0ec9fa14-73cd-e211-be08-d229661189ee&emailType=Inv
iteFirstReminder&sdate=201306050024&utm_source=EmailInviteFirstReminder&utm_mediu
m=Email&sendercc=EG&emailLinkType=MainCallToAction>

reply+i-13736431-b00e539f49385a604433a684a46d078b57305be7-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=bV5LbsbsUeqYGRx
GLpoCw2dO5mm-MHEAP_83A87YOe0.eyJlbWFpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4
NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJlNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzcwMzkxODkwIiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=0ec9fa14-73cd-e
211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_source
=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=Unsubscribe>
.

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=KgpLDPqsIdD
ZqxTjMkp-EbhA3th_WZy05zUZuSihNNw.eyJlbWFpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0
OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJlNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmc
m9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtYzk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05Zj
VkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc3N1ZWRfYXQiOiIxMzcwOTk2Nzg0IiwidmVyIjoiMSI
sInAiOiIzIn0&emailMessageId=e9672e48-f3d2-e211-884e-85d1397596ad&emailType=Invite
SecondReminder&sdate=201306120026&utm_source=EmailInviteSecondReminder&utm_medium
=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy Atef is still waiting to connect with you.

<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=ftux/emaili
nvitelanding?signedParameters=KgpLDPqsIdDZqxTjMkp-EbhA3th_WZy05zUZuSihNNw.eyJlbWF
pbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJl
Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtY
zk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05ZjVkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc3
N1ZWRfYXQiOiIxMzcwOTk2Nzg0IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=e9672e48-f3d
2-e211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120026&utm_so
urce=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Profile
Thumb>

Beshoy Atef
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=ftux/emaili
nvitelanding?signedParameters=KgpLDPqsIdDZqxTjMkp-EbhA3th_WZy05zUZuSihNNw.eyJlbWF
pbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJl
Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtY
zk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05ZjVkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc3
N1ZWRfYXQiOiIxMzcwOTk2Nzg0IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=e9672e48-f3d
2-e211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120026&utm_so
urce=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Profile
Name>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=KgpLDPqsIdD
ZqxTjMkp-EbhA3th_WZy05zUZuSihNNw.eyJlbWFpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0
OTM4NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJlNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmc
m9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtYzk2NTI1OWJmMTg2IiwidG8iOiIwM2M0Nzc5ZS05Zj
VkLTUyYjMtODNlMi01MzFiNzVhMDRjZDMiLCJpc3N1ZWRfYXQiOiIxMzcwOTk2Nzg0IiwidmVyIjoiMSI
sInAiOiIzIn0&emailMessageId=e9672e48-f3d2-e211-884e-85d1397596ad&emailType=Invite
SecondReminder&sdate=201306120026&utm_source=EmailInviteSecondReminder&utm_medium
=Email&sendercc=EG&emailLinkType=MainCallToAction>

reply+i-13736431-b00e539f49385a604433a684a46d078b57305be7-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=qSMPwr7IiHl0Qa_
zQH1dnV_XfkhZAB8nZvEl3uiZk4E.eyJlbWFpbCI6InJlcGx5K2ktMTM3MzY0MzEtYjAwZTUzOWY0OTM4
NWE2MDQ0MzNhNjg0YTQ2ZDA3OGI1NzMwNWJlNy0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzcwOTk2Nzg0IiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=e9672e48-f3d2-e
211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120026&utm_sourc
e=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Unsubscrib
e> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Pull request closed without merging**
