### PR TITLE
C3 reem refining bar2

### PR DESCRIPTION
**Pull request by Reem-Sharkawy**
@nadeembarakat  @saraismail1234  @mohamedhammad89  @iBebarz 
 please review 
 however notice you have to type the url : homepage/ 
until my work with beshoy is integrated

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
can you offer me with some dummy data please??

**Comment by abdelrahmanMaged** [comment]
@Reem-Sharkawy kindly be notified that i started to review the branch 
however whenever i try to refine anything i just get that label.

please select some subchannels to view.
knowing that i already chosen subchannels.
Regards,

**Comment by Reem-Sharkawy** [comment]
could you wait please , because now i runed the server and its not running !

**Comment by BeshoyAtef** [comment]
nice Code :+1:

**Comment by abdelrahmanMaged** [comment]
take your time and when you are done please tag me
regards,

**Comment by Reem-Sharkawy** [comment]
please review !

**Comment by Reem-Sharkawy** [comment]
@HebaElSobky kindly review

**Comment by Reem-Sharkawy** [comment]
#103

**Comment by HebaElSobky** [comment]
send me the link

**Comment by Reem-Sharkawy** [comment]
https://github.com/DinaSaad/sharesoft-13/pull/246

**Comment by HebaElSobky** [comment]
Reem Howa l branch daa l Howa u only want to see specific subchannels of
channels ??

**Comment by Reem-Sharkawy** [comment]
l2 dhh , el mfroud kol el subchannel fel 2wel clicked w babtdyy 23mel
unclick w ye5tfoo m3akii

**Comment by HebaElSobky** [comment]
yes da l ana asdii 3aliih

**Comment by HebaElSobky** [comment]
okaay then @Reem-Sharkawy scenario is verified check with the other reviewer to merge your branch

**Comment by Reem-Sharkawy** [comment]
@saraismail1234  @iBebarz  @mohamedhammad89 
could you review please !

**Comment by ahmedshireef** [comment]
UML reviewed

**Pull request merged**
