### PR TITLE
C1 hala admin4

### PR DESCRIPTION
**Pull request by HalaKamal**
@AbdelrahmanAyad  please review me

### CODE REVIEW

**Comment by Tharwat7** [comment]
@HalaKamal 
Y havent u tagged the rest of the reviewers???
and please link the request to ur issue number

**Comment by abdelrahmanMaged** [comment]
kindly be notified that i get this error when i try to access a post.

TemplateSyntaxError at /showpost

Invalid block tag: 'endblock', expected 'endif'

**Comment by HalaKamal** [comment]
@BeshoSmile  please review me , @Tharwat7 please review me and the issue is #108

**Comment by HalaKamal** [comment]
@abdelrahmanMaged  @BeshoSmile

**Comment by BeshoyAtef** [comment]
why u made another branch ?

**Comment by abdelrahmanMaged** [comment]
@HalaKamal  kindly be notified that the hide button is not functioning 

Please fix it

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=h8b79_tHi_p4GVcd1Mgd4cgA9kM7eud9onS2b765fak.eyJlbW
FpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY
0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOGUwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=4a29f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy Atef wants to connect with you.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=h8b79_tHi_p4GVcd1Mgd4cgA9kM7eud9onS2b765fak.eyJlbW
FpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY
0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOGUwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=4a29f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=ProfileThumb>

Beshoy Atef
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=h8b79_tHi_p4GVcd1Mgd4cgA9kM7eud9onS2b765fak.eyJlbW
FpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY
0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOGUwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=4a29f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=ProfileName>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=h8b79_tHi_p4GVcd1Mgd4cgA9kM7eud9onS2b765fak.eyJlbW
FpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY
0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOGUwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&cnId=88470b98-4248-e011-88
9f-c965259bf186&emailMessageId=4a29f5ef-7dc8-e211-a4c9-c701ce909180&emailType=Inv
ite&sdate=201305291636&utm_source=EmailInvite&utm_medium=Email&sendercc=EG&emailL
inkType=MainCallToAction>

reply+i-13780843-bb4fc812a933925b21096bf716d685c97b055f47-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=t3QJgK9-8Lplik6
mzxpSOq_ZmBsfo2IevetXMEKOnF0.eyJlbWFpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMz
OTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=4a29f5ef-7dc8-e
211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInvite&
utm_medium=Email&sendercc=EG&emailLinkType=Unsubscribe> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=JvtHLn9btzrh3RWRSmHpH6uWhFEcwvaM-x5N2i06pOY.eyJlbW
FpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY
0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOGUwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODc4IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=08c9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy is waiting for you to accept this pending invitation.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=JvtHLn9btzrh3RWRSmHpH6uWhFEcwvaM-x5N2i06pOY.eyJlbW
FpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY
0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOGUwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODc4IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=08c9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=ProfileT
humb>

Beshoy Atef
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=JvtHLn9btzrh3RWRSmHpH6uWhFEcwvaM-x5N2i06pOY.eyJlbW
FpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY
0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOGUwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODc4IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=08c9fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=ProfileN
ame>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=JvtHLn9btzrh3RWRSmHpH6uWhFEcwvaM-x5N2i06pOY.eyJlbW
FpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY
0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOGUwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODc4IiwidmVyIjoiMSIsInAiOiIzIn0&cnId=88470b98-4248-e011-88
9f-c965259bf186&emailMessageId=08c9fa14-73cd-e211-be08-d229661189ee&emailType=Inv
iteFirstReminder&sdate=201306050024&utm_source=EmailInviteFirstReminder&utm_mediu
m=Email&sendercc=EG&emailLinkType=MainCallToAction>

reply+i-13780843-bb4fc812a933925b21096bf716d685c97b055f47-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=-ujIj8aWcGGZIOU
m2fvNjLVY6bioN9N--WJKlcSw5_Q.eyJlbWFpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMz
OTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzcwMzkxODc4IiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=08c9fa14-73cd-e
211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_source
=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=Unsubscribe>
.

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=dg6dyyXdFDP
cuJN6jGoda-Q4vh2Y4yJKhhDpoSOY-18.eyJlbWFpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJh
OTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmc
m9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtYzk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOG
UwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc3N1ZWRfYXQiOiIxMzcwOTk2NjM5IiwidmVyIjoiMSI
sInAiOiIzIn0&emailMessageId=7e672e48-f3d2-e211-884e-85d1397596ad&emailType=Invite
SecondReminder&sdate=201306120023&utm_source=EmailInviteSecondReminder&utm_medium
=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy Atef is still waiting to connect with you.

<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=ftux/emaili
nvitelanding?signedParameters=dg6dyyXdFDPcuJN6jGoda-Q4vh2Y4yJKhhDpoSOY-18.eyJlbWF
pbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY0
Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtY
zk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOGUwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc3
N1ZWRfYXQiOiIxMzcwOTk2NjM5IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=7e672e48-f3d
2-e211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120023&utm_so
urce=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Profile
Thumb>

Beshoy Atef
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=ftux/emaili
nvitelanding?signedParameters=dg6dyyXdFDPcuJN6jGoda-Q4vh2Y4yJKhhDpoSOY-18.eyJlbWF
pbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY0
Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtY
zk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOGUwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc3
N1ZWRfYXQiOiIxMzcwOTk2NjM5IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=7e672e48-f3d
2-e211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120023&utm_so
urce=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Profile
Name>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=dg6dyyXdFDP
cuJN6jGoda-Q4vh2Y4yJKhhDpoSOY-18.eyJlbWFpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJh
OTMzOTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmc
m9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtYzk2NTI1OWJmMTg2IiwidG8iOiJhOWYyZTNlNi1hOG
UwLTU3YTMtOTcwMS0zMGFkMDJhZWFmOTkiLCJpc3N1ZWRfYXQiOiIxMzcwOTk2NjM5IiwidmVyIjoiMSI
sInAiOiIzIn0&emailMessageId=7e672e48-f3d2-e211-884e-85d1397596ad&emailType=Invite
SecondReminder&sdate=201306120023&utm_source=EmailInviteSecondReminder&utm_medium
=Email&sendercc=EG&emailLinkType=MainCallToAction>

reply+i-13780843-bb4fc812a933925b21096bf716d685c97b055f47-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=DbT3AMI_z9AhFvF
EVLJx3OUk5NJGsZbnaCWzaHZl2bk.eyJlbWFpbCI6InJlcGx5K2ktMTM3ODA4NDMtYmI0ZmM4MTJhOTMz
OTI1YjIxMDk2YmY3MTZkNjg1Yzk3YjA1NWY0Ny0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzcwOTk2NjM5IiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=7e672e48-f3d2-e
211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120023&utm_sourc
e=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Unsubscrib
e> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Pull request closed without merging**
