### PR TITLE
C1 beshoy sprint0

### PR DESCRIPTION
**Pull request by BeshoyAtef**
@AbdelrahmanAyad @HalaKamal @Tharwat7 

Please CHeck my Code

### CODE REVIEW

**Comment by HalaKamal** [comment]
besho did you upload your diagram?

**Comment by BeshoyAtef** [comment]
nope i am doing it now
hala ana mesh la2y ur code walla ur issue

**Comment by BeshoyAtef** [comment]
@HalaKamal  Check my digram 
@Tharwat7  check my code please

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=5WI35kJ1Q8GAv9oBQochGvwe36hBds12DybrXWz5n60.eyJlbW
FpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZ
kMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOGEzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=3929f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy Atef wants to connect with you.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=5WI35kJ1Q8GAv9oBQochGvwe36hBds12DybrXWz5n60.eyJlbW
FpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZ
kMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOGEzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=3929f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=ProfileThumb>

Beshoy Atef
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=5WI35kJ1Q8GAv9oBQochGvwe36hBds12DybrXWz5n60.eyJlbW
FpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZ
kMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOGEzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=3929f5ef-7d
c8-e211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInv
ite&utm_medium=Email&sendercc=EG&emailLinkType=ProfileName>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=5WI35kJ1Q8GAv9oBQochGvwe36hBds12DybrXWz5n60.eyJlbW
FpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZ
kMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOGEzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc
3N1ZWRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIzIn0&cnId=88470b98-4248-e011-88
9f-c965259bf186&emailMessageId=3929f5ef-7dc8-e211-a4c9-c701ce909180&emailType=Inv
ite&sdate=201305291636&utm_source=EmailInvite&utm_medium=Email&sendercc=EG&emailL
inkType=MainCallToAction>

reply+i-12532841-33ac47ed201bff0eb3ca3d9a0526012b3f0066d2-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=9dsS-FshKktXgko
wMby62gk37yHt_bDppEZ48hmq9c0.eyJlbWFpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFi
ZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZkMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzY5ODQ1NDA2IiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=3929f5ef-7dc8-e
211-a4c9-c701ce909180&emailType=Invite&sdate=201305291636&utm_source=EmailInvite&
utm_medium=Email&sendercc=EG&emailLinkType=Unsubscribe> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=1z7-jFu9Wo17feeX7AyrpvtqZlq_1VrOFKkSRmhE8s8.eyJlbW
FpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZ
kMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOGEzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODUxIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=ffc8fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy is waiting for you to accept this pending invitation.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=1z7-jFu9Wo17feeX7AyrpvtqZlq_1VrOFKkSRmhE8s8.eyJlbW
FpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZ
kMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOGEzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODUxIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=ffc8fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=ProfileT
humb>

Beshoy Atef
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=1z7-jFu9Wo17feeX7AyrpvtqZlq_1VrOFKkSRmhE8s8.eyJlbW
FpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZ
kMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOGEzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODUxIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=ffc8fa14-73
cd-e211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_so
urce=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=ProfileN
ame>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=88470b98-4248-e011-889f
-c965259bf186&signedParameters=1z7-jFu9Wo17feeX7AyrpvtqZlq_1VrOFKkSRmhE8s8.eyJlbW
FpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZ
kMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYt
Yzk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOGEzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc
3N1ZWRfYXQiOiIxMzcwMzkxODUxIiwidmVyIjoiMSIsInAiOiIzIn0&cnId=88470b98-4248-e011-88
9f-c965259bf186&emailMessageId=ffc8fa14-73cd-e211-be08-d229661189ee&emailType=Inv
iteFirstReminder&sdate=201306050024&utm_source=EmailInviteFirstReminder&utm_mediu
m=Email&sendercc=EG&emailLinkType=MainCallToAction>

reply+i-12532841-33ac47ed201bff0eb3ca3d9a0526012b3f0066d2-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=6MlB6AGN6Z3gT5y
zWeWs-S-vO9wahHO562YjP8RERHg.eyJlbWFpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFi
ZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZkMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzcwMzkxODUxIiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=ffc8fa14-73cd-e
211-be08-d229661189ee&emailType=InviteFirstReminder&sdate=201306050024&utm_source
=EmailInviteFirstReminder&utm_medium=Email&sendercc=EG&emailLinkType=Unsubscribe>
.

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by BeshoyAtef** [comment]
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=fOoo4hITIbT
-D5YQkaNyw-qG5BWleKN0t54gSryVtcc.eyJlbWFpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQy
MDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZkMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmc
m9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtYzk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOG
EzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc3N1ZWRfYXQiOiIxMzcwOTk2ODEzIiwidmVyIjoiMSI
sInAiOiIzIn0&emailMessageId=a8662e48-f3d2-e211-884e-85d1397596ad&emailType=Invite
SecondReminder&sdate=201306120026&utm_source=EmailInviteSecondReminder&utm_medium
=Email&sendercc=EG&emailLinkType=Logo>

Hi,

Beshoy Atef is still waiting to connect with you.

<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=ftux/emaili
nvitelanding?signedParameters=fOoo4hITIbT-D5YQkaNyw-qG5BWleKN0t54gSryVtcc.eyJlbWF
pbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZk
Mi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtY
zk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOGEzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc3
N1ZWRfYXQiOiIxMzcwOTk2ODEzIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=a8662e48-f3d
2-e211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120026&utm_so
urce=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Profile
Thumb>

Beshoy Atef
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=ftux/emaili
nvitelanding?signedParameters=fOoo4hITIbT-D5YQkaNyw-qG5BWleKN0t54gSryVtcc.eyJlbWF
pbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZk
Mi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmcm9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtY
zk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOGEzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc3
N1ZWRfYXQiOiIxMzcwOTk2ODEzIiwidmVyIjoiMSIsInAiOiIzIn0&emailMessageId=a8662e48-f3d
2-e211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120026&utm_so
urce=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Profile
Name>

Invite sent: 29 May, 2013

Continue
<http://www.skillpages.com/i/ftux/emailinvitelanding?signedParameters=fOoo4hITIbT
-D5YQkaNyw-qG5BWleKN0t54gSryVtcc.eyJlbWFpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQy
MDFiZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZkMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJmc
m9tIjoiODg0NzBiOTgtNDI0OC1lMDExLTg4OWYtYzk2NTI1OWJmMTg2IiwidG8iOiI2MDUzMjNiOS0zOG
EzLTU0OWEtOTI3Ni1kY2MxYWNlYjZmOWQiLCJpc3N1ZWRfYXQiOiIxMzcwOTk2ODEzIiwidmVyIjoiMSI
sInAiOiIzIn0&emailMessageId=a8662e48-f3d2-e211-884e-85d1397596ad&emailType=Invite
SecondReminder&sdate=201306120026&utm_source=EmailInviteSecondReminder&utm_medium
=Email&sendercc=EG&emailLinkType=MainCallToAction>

reply+i-12532841-33ac47ed201bff0eb3ca3d9a0526012b3f0066d2-3515278@reply.github.co
m was invited to join SkillPages by Beshoy Atef. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=r-Rp-b6GvNAxpoy
7zDQ-Y79YCxNqGyz5uk1568AZ3X8.eyJlbWFpbCI6InJlcGx5K2ktMTI1MzI4NDEtMzNhYzQ3ZWQyMDFi
ZmYwZWIzY2EzZDlhMDUyNjAxMmIzZjAwNjZkMi0zNTE1Mjc4QHJlcGx5LmdpdGh1Yi5jb20iLCJpc3N1Z
WRfYXQiOiIxMzcwOTk2ODEzIiwidmVyIjoiMSIsInAiOiIwIn0&emailMessageId=a8662e48-f3d2-e
211-884e-85d1397596ad&emailType=InviteSecondReminder&sdate=201306120026&utm_sourc
e=EmailInviteSecondReminder&utm_medium=Email&sendercc=EG&emailLinkType=Unsubscrib
e> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Pull request closed without merging**
