### PR TITLE
C2 heba test sprint2

### PR DESCRIPTION
**Pull request by HebaElSobky**
@mahmoudHussein @maizaied @mohamedahmedawad93 these are the test please review and merge

### CODE REVIEW

**Comment by mahmoudHussein** [comment]
@HebaElSobky tests ran el7

**Comment by HebaElSobky** [comment]
Msh mesada2a :D
BGD ??!!!

Sent from my iPhone,
Heba A. El-Sobky :)

**Comment by HebaElSobky** [comment]
Tb is it green can u mergee?

Sent from my iPhone,
Heba A. El-Sobky :)

**Comment by mahmoudHussein** [comment]
@HebaElSobky please check the tests and tag me again

**Comment by HebaElSobky** [comment]
@mahmoudHussein please review again it runs now :)

**Comment by HebaElSobky** [comment]
@mahmoudHussein ??

**Pull request merged**
