### PR TITLE
Templates v2

### PR DESCRIPTION
**Pull request by mahmoudHussein**
@mohamedahmedawad93 @HebaElSobky @maizaied please review and merge my template files !

### CODE REVIEW

**Comment by abdelrahmanMaged** [comment]
mahmoud you removed the ViewSubChannel.js however this js will make my point functioning disabling it will affect the functionality so please modify it

**Comment by mahmoudHussein** [comment]
Abd el rahman that's part of your code so I shouldn't be submitting it .... So what u can do is after the file is merged u add it to the base file ! Or even better I'll be pushing a file named custom.js in a bit for us all to put our customed js in ! In both cases don't worry ! 
Sent from my BlackBerry® from Vodafone

-----Original Message-----

**Comment by abdelrahmanMaged** [comment]
Ok i was just notifying you that we will need to add more javascripts.

Regards,

**Comment by mohamedahmedawad93** [comment]
@mahmoudHussein your code is valid

**Comment by HebaElSobky** [comment]
@mahmoudHussein  no scenario to be tested here #125

**Comment by mahmoudHussein** [comment]
Please merge then ! Because people need to use the templates ! 
Sent from my BlackBerry® from Vodafone

-----Original Message-----

**Pull request merged**
