### PR TITLE
I added the refining bar to refine channels and subchannels

### PR DESCRIPTION
**Pull request by Reem-Sharkawy**
@iBebarz @saraismail1234 @nadeembarakat @mohamedhammad89 
please review my code
#103

### CODE REVIEW

**Comment by BeshoyAtef** [comment]
#103

**Comment by Reem-Sharkawy** [comment]
@HebaElSobky please review

**Comment by HebaElSobky** [comment]
@Reem-Sharkawy bravoo reemo ur ready to go BUT BEFORE MERGING please REMOVE the attributes dic and tell me again to merge :) :+1:

**Comment by Reem-Sharkawy** [comment]
happy done :D

**Pull request merged**
